datastore:
  image: busybox
  tty: true
  volumes:
    - /var/lib/postgresql/data
    - /data
    - /myapp/public
    - /myapp/tmp/sockets

db:
  image: postgres:9.5.0
  volumes_from:
    - datastore

redis:
  image: redis:3.0.7
  volumes_from:
    - datastore

nginx:
  image: nginx:1.9.10
  ports:
    - "8000:80"
  volumes:
    - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./containers/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
  volumes_from:
    - datastore
  links:
    - app

app:
  build: .
  command: bash -c "rm -f tmp/pids/unicorn.pid && unicorn_rails -c config/unicorn.rb"
  environment:
    RAILS_ENV: development
  volumes:
    - .:/myapp
  volumes_from:
    - datastore
  links:
    - db
    - redis
