version: '2'
services:
  db:
    image: mysql:5.6
    volumes:
      - './data:/var/lib/mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  app:
    build: .
    command: bundle exec rails s -p 30000 -b '0.0.0.0'
    volumes:
      - .:/myapp:cached
    ports:
      - "30000:30000"
    depends_on:
      - db
