db:
  image: postgres
app:
  build: .
  command: bundle exec unicorn_rails -E development -c config/unicorn.rb
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
nginx:
  image: nginx
  ports:
    - "8000:80"
  links:
    - app
  volumes:
    - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./containers/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
