default: &default
  host: redis
  port: 6379
  db: 0
  session_db: 2
  cache_db: 3

development:
  <<: *default
  namespace: "myapp_dev"

test:
  <<: *default
  db: 1
  namespace: "myapp_test"

production:
  <<: *default
  host: # TODO:elasticache endpoint
  namespace: "myapp_pro"
